name: Build and Push HSEmotion model as Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch: # Allow manual triggering from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install MLServer
      run: pip install mlserver

    - name: Build Hsemotion Docker image
      run: |
        mlserver build hsemotion/ -t ${{ secrets.DOCKER_REGISTRY }}/oele-hsemotion:latest

    - name: Build Yolo Docker image
      run: |
        mlserver build yolo/ -t ${{ secrets.DOCKER_REGISTRY }}/oele-yolo:latest


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_REGISTRY }}/oele-hsemotion:latest .
        docker push ${{ secrets.DOCKER_REGISTRY }}/oele-yolo:latest 

